# Generated by Django 4.2.6 on 2023-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('sartuday', 'Sartuday'), ('sunday', 'Sunday')], max_length=200, unique=True),
        ),
    ]
