# Generated by Django 4.2.5 on 2023-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shortintro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
